# Utiliser une image Python officielle comme base
FROM python:3.9-slim

# Définir le répertoire de travail à l'intérieur du conteneur
WORKDIR /app

# Copier le fichier requirements.txt dans le conteneur
COPY requirements.txt requirements.txt

# Installer les dépendances Python
RUN pip install -r requirements.txt

# Copier tous les fichiers du projet dans le conteneur
COPY . .

# Définir la commande pour démarrer l'application Flask
CMD ["python", "app.py"]
